# These are supported funding model platforms

community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2, user3, user4]
issuehunt: # Replace with a single IssueHunt username
ko_fi: k4izokage
liberapay: # Replace with a single Liberapay username
open_collective: # Replace with a single Open Collective username
patreon: # Replace with a single Patreon username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
polar: # Replace with a single Polar username
buy_me_a_coffee: k4izokage
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']